Display the reason which failed certificate generation fails within cloud.server.ConfigurationServerImpl.generateDefaultKeystore
Description:

The reason which failed in generation of the certificate is not displayed now.
At that time, IOException which does not include the reason is raised.
In order to solve the problem quickly, the reason should be included in the message.

(Now)
WARN  [cloud.server.ConfigurationServerImpl] (main:) Would use fail-safe keystore to continue.
java.io.IOException: Fail to generate certificate!
    at com.cloud.server.ConfigurationServerImpl.generateDefaultKeystore(ConfigurationServerImpl.java:490)

(Fix)
WARN  [cloud.server.ConfigurationServerImpl] (main:) Would use fail-safe keystore to continue.
java.io.IOException: Fail to generate certificate!: sudo: sorry, you must have a tty to run sudo
    at com.cloud.server.ConfigurationServerImpl.generateDefaultKeystore(ConfigurationServerImpl.java:490)

Testing Completed:

mvn clean install
mvn -pl :cloud-client-ui jetty:run

And generation of the certificate was made to fail, checked it.

Signed-off-by: Chip Childers <chip.childers@gmail.com>