SnapshotDetailsVO doesn't have a display field even though it is required in the searchbuilder in ResourceDetailsDaoBase
java.lang.AssertionError: Searching for a field that's not there: display
    at com.cloud.utils.db.SearchBase.set(SearchBase.java:219)
    at com.cloud.utils.db.SearchBase$Interceptor.intercept(SearchBase.java:475)