veeam: fix authorization failure in veeam 12a
marvin.cloudstackException.CloudstackAPIException: Execute cmd: listbackupproviderofferings failed, due to: errorCode: 530, errorText:Veeam B&R API call unauthorized, please ask your administrator to fix integration issues.

v1_4 is not supported in veeam 12a, refer to https://helpcenter.veeam.com/docs/backup/em_rest/http_authentication.html?ver=120