CLOUDSTACK-2195: Don't return a UserVM object if we fail to stop vm
pass back null if we fail to connect to agent or stop the vm, rather
than something that looks like success to the stopVirtualMachine api
command.

Testing:

Applied to 4.1 branch, attempted to stop VM with KVM agent disconnected,
finally saw it fail. The logs also showed why, which is good:

2013-04-25 17:37:09,933 ERROR [cloud.vm.VirtualMachineManagerImpl]
(Job-Executor-1:job-44) Unable to stop vm, agent unavailable:
com.cloud.exception.AgentUnavailableException: Resource [Host:1] is
unreachable: Host 1: Host with specified id is not in the right state:
Disconnected

Started the KVM agent, and stopping succeeded.

Signed-off-by: Chip Childers <chip.childers@gmail.com>